import type { DrillContent, SportId } from "../types";

type D = Partial<DrillContent> & { id: string; name: string; instructions: string; skillTrackId: string };

const make = (sportId: SportId, core: string[], list: D[]): DrillContent[] =>
  list.map((d) => ({
    sportId, durationSec: 120, difficulty: 2, ageMin: 8, ageMax: 13, minSpace: "small", needsWall: false, needsGoalOrHoop: false,
    equipmentRequired: d.isShadow ? [] : core, equipmentOptional: [], positionIds: [], xp: 10, isShadow: false,
    ...d, skillTrackId: `${sportId}_${d.skillTrackId}`,
  }));

export const drills: DrillContent[] = [
  ...make("soccer", ["soccer_ball"], [
    { id: "soc_toe_taps", skillTrackId: "control", name: "Toe Taps", instructions: "Tap the top of the ball with one foot, then the other. Go fast but stay light.", difficulty: 1, durationSec: 90, xp: 5 },
    { id: "soc_shadow_touches", skillTrackId: "control", name: "Shadow Touches", instructions: "Pretend a ball is there. Tap inside, outside, inside, outside.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "soc_wall_pass", skillTrackId: "passing", name: "Wall Passes", instructions: "Pass into the wall and control the bounce back. Use both feet.", difficulty: 2, durationSec: 180, needsWall: true },
    { id: "soc_target_pass", skillTrackId: "passing", name: "Target Pass", instructions: "Put a shoe 5 steps away. Pass and hit it. Try 10 times.", difficulty: 2, durationSec: 150, equipmentOptional: ["cones"] },
    { id: "soc_shadow_pass", skillTrackId: "passing", name: "Air Passes", instructions: "Step and swing your passing foot. Lock your ankle. No ball needed.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "soc_cone_dribble", skillTrackId: "dribbling", name: "Cone Weave", instructions: "Dribble through 4 cones and back. Small touches.", difficulty: 2, durationSec: 180, equipmentRequired: ["soccer_ball", "cones"], minSpace: "medium" },
    { id: "soc_box_dribble", skillTrackId: "dribbling", name: "Box Dribble", instructions: "Dribble in a small square. Change direction every 3 touches.", difficulty: 2, durationSec: 150 },
    { id: "soc_shadow_dribble", skillTrackId: "dribbling", name: "Ghost Dribble", instructions: "Zig-zag across the room like you have the ball. Fake left, go right.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "soc_finish", skillTrackId: "shooting", name: "Finish at Target", instructions: "Set the ball, take 2 steps, and shoot at the goal. Aim low corner.", difficulty: 3, durationSec: 240, needsGoalOrHoop: true, minSpace: "medium", xp: 15 },
    { id: "soc_wall_shot", skillTrackId: "shooting", name: "Wall Shots", instructions: "Shoot into the wall with your laces. Control the rebound and go again.", difficulty: 3, durationSec: 200, needsWall: true, xp: 12 },
    { id: "soc_shadow_shot", skillTrackId: "shooting", name: "Shadow Strikes", instructions: "Plant your foot, swing through, and land on your kicking foot.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "soc_juggle", skillTrackId: "control", name: "Juggling Ladder", instructions: "Juggle 5 times, then 10, then 20. Thighs count.", difficulty: 4, durationSec: 240, xp: 15 },
    { id: "soc_gk_catch", skillTrackId: "position", name: "Catch and Set", instructions: "Toss the ball up, catch it with a W shape, and set your feet.", difficulty: 2, durationSec: 150, positionIds: ["soccer_gk"] },
    { id: "soc_first_touch", skillTrackId: "position", name: "First Touch Turns", instructions: "Roll the ball ahead, take one touch to turn, then move away.", difficulty: 3, durationSec: 180 },
    { id: "soc_shadow_position", skillTrackId: "position", name: "Shuffle and Set", instructions: "Shuffle side to side, then freeze in a ready stance. Repeat.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
  ]),
  ...make("basketball", ["basketball"], [
    { id: "bb_pound", skillTrackId: "handles", name: "Pound Dribble", instructions: "Dribble hard at knee height. Right hand 20, left hand 20.", difficulty: 1, durationSec: 120, xp: 5 },
    { id: "bb_crossover", skillTrackId: "handles", name: "Crossover Series", instructions: "Cross the ball in front, then between your legs. Keep your eyes up.", difficulty: 3, durationSec: 180, xp: 12 },
    { id: "bb_shadow_handles", skillTrackId: "handles", name: "Air Dribble", instructions: "Do the dribble moves without a ball. Stay low and quick.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "bb_wall_pass", skillTrackId: "passing", name: "Wall Chest Pass", instructions: "Chest pass into the wall and catch it. Step into every pass.", difficulty: 2, durationSec: 150, needsWall: true },
    { id: "bb_shadow_pass", skillTrackId: "passing", name: "Pass Shapes", instructions: "Chest pass, bounce pass, overhead. Step and snap your wrists.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "bb_form_shot", skillTrackId: "shooting", name: "Form Shooting", instructions: "Stand close. Shoot with one hand and hold your follow-through.", difficulty: 2, durationSec: 180, equipmentOptional: ["hoop"] },
    { id: "bb_spot_shots", skillTrackId: "shooting", name: "Five Spots", instructions: "Shoot from 5 spots around the hoop. Make 2 at each before you move.", difficulty: 3, durationSec: 300, needsGoalOrHoop: true, minSpace: "medium", xp: 15 },
    { id: "bb_shadow_shot", skillTrackId: "shooting", name: "Shadow Shot", instructions: "Bend your knees, lift, and flick your wrist. Freeze the follow-through.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "bb_layup_steps", skillTrackId: "finishing", name: "Layup Footwork", instructions: "Right foot, left foot, jump. Reach the ball up high.", difficulty: 2, durationSec: 150, minSpace: "medium" },
    { id: "bb_mikan", skillTrackId: "finishing", name: "Mikan Drill", instructions: "Layup on the right, catch, layup on the left. Keep going.", difficulty: 3, durationSec: 180, needsGoalOrHoop: true, xp: 12 },
    { id: "bb_shadow_finish", skillTrackId: "finishing", name: "Step-Step-Jump", instructions: "Practice the layup steps with no ball. Land soft.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "bb_slides", skillTrackId: "defense", name: "Defensive Slides", instructions: "Stay low. Slide 5 steps left, 5 steps right. Don't cross your feet.", difficulty: 2, durationSec: 120, isShadow: true },
    { id: "bb_closeout", skillTrackId: "defense", name: "Closeouts", instructions: "Sprint 3 steps, then chop your feet and get a hand up.", difficulty: 2, durationSec: 120, equipmentOptional: ["cones"], isShadow: true },
  ]),
  ...make("football", ["football"], [
    { id: "fb_high_tight", skillTrackId: "security", name: "High and Tight", instructions: "Tuck the ball high under your arm. Jog and switch arms every 10 steps.", difficulty: 1, durationSec: 120, xp: 5 },
    { id: "fb_gauntlet", skillTrackId: "security", name: "Carry Gauntlet", instructions: "Run past 4 cones. Switch the ball to the outside arm at each one.", difficulty: 3, durationSec: 150, equipmentRequired: ["football", "cones"], minSpace: "medium", xp: 12 },
    { id: "fb_shadow_carry", skillTrackId: "security", name: "Tuck Drill", instructions: "Pretend to catch, then tuck. Elbow tight, fingers over the point.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "fb_drop_throw", skillTrackId: "throwing", name: "3-Step Drop", instructions: "Drop back 3 steps, plant, and throw at a target on the wall.", difficulty: 3, durationSec: 180, needsWall: true, minSpace: "medium", xp: 12 },
    { id: "fb_target_throw", skillTrackId: "throwing", name: "Target Throws", instructions: "Throw at a spot 10 steps away. Point your front foot at it.", difficulty: 2, durationSec: 150, minSpace: "medium" },
    { id: "fb_shadow_throw", skillTrackId: "throwing", name: "Air Throws", instructions: "Step, turn your hips, and follow through. No ball needed.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "fb_route_tree", skillTrackId: "routes", name: "Route Tree", instructions: "Run a slant, an out, and a go. Sharp cuts, then sprint.", difficulty: 2, durationSec: 240, minSpace: "large", equipmentOptional: ["cones"], isShadow: true },
    { id: "fb_cut_steps", skillTrackId: "routes", name: "Cut Steps", instructions: "Run 3 steps, plant your outside foot, and cut hard. Both ways.", difficulty: 2, durationSec: 120, isShadow: true },
    { id: "fb_soft_hands", skillTrackId: "catching", name: "Soft Hands", instructions: "Toss the ball up and catch it with your fingertips. Look it in.", difficulty: 1, durationSec: 120, xp: 5 },
    { id: "fb_wall_catch", skillTrackId: "catching", name: "Wall Catch", instructions: "Throw at the wall and catch the bounce. Make a diamond with your hands.", difficulty: 2, durationSec: 150, needsWall: true },
    { id: "fb_shadow_catch", skillTrackId: "catching", name: "Diamond Hands", instructions: "Make a diamond with your thumbs and fingers. Snap it shut 20 times.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "fb_mirror", skillTrackId: "defense", name: "Mirror Shuffle", instructions: "Shuffle side to side like you're following a runner. Stay low.", difficulty: 2, durationSec: 120, isShadow: true },
    { id: "fb_flag_pull", skillTrackId: "defense", name: "Flag Pull Reach", instructions: "Step, bend at the knees, and swipe low with one hand. Both sides.", difficulty: 2, durationSec: 120, isShadow: true },
  ]),
  ...make("tennis", ["racket", "tennis_ball"], [
    { id: "tn_bounce_up", skillTrackId: "feel", name: "Bounce-Ups", instructions: "Bounce the ball up on your racket. Count how many in a row.", difficulty: 1, durationSec: 120, xp: 5 },
    { id: "tn_bounce_down", skillTrackId: "feel", name: "Bounce-Downs", instructions: "Bounce the ball on the ground with your racket. Walk while you do it.", difficulty: 2, durationSec: 120 },
    { id: "tn_shadow_feel", skillTrackId: "feel", name: "Racket Flips", instructions: "Hold your racket and flip it grip to grip. Find the forehand grip fast.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true, equipmentOptional: ["racket"] },
    { id: "tn_wall_fh", skillTrackId: "forehand", name: "Wall Rally Forehand", instructions: "Rally against the wall with forehands only. Aim for 10 in a row.", difficulty: 3, durationSec: 240, needsWall: true, minSpace: "medium", xp: 12 },
    { id: "tn_drop_fh", skillTrackId: "forehand", name: "Drop-Hit Forehand", instructions: "Drop the ball, let it bounce, and swing low to high.", difficulty: 2, durationSec: 150, minSpace: "medium" },
    { id: "tn_shadow_fh", skillTrackId: "forehand", name: "Shadow Forehand", instructions: "Turn sideways, swing low to high, finish over your shoulder.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "tn_wall_bh", skillTrackId: "backhand", name: "Wall Rally Backhand", instructions: "Rally against the wall with backhands only. Two hands is fine.", difficulty: 3, durationSec: 240, needsWall: true, minSpace: "medium", xp: 12 },
    { id: "tn_shadow_bh", skillTrackId: "backhand", name: "Shadow Backhand", instructions: "Turn the other way, swing low to high. Keep your head still.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "tn_toss", skillTrackId: "serve", name: "Serve Toss", instructions: "Toss the ball straight up in front of you. Let it land on a target.", difficulty: 2, durationSec: 120, equipmentRequired: ["tennis_ball"] },
    { id: "tn_wall_serve", skillTrackId: "serve", name: "Wall Serves", instructions: "Serve into the wall above a line. Reach up tall.", difficulty: 4, durationSec: 200, needsWall: true, minSpace: "medium", xp: 15 },
    { id: "tn_shadow_serve", skillTrackId: "serve", name: "Trophy Pose", instructions: "Toss arm up, racket back, freeze like a trophy. Then swing up.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "tn_split", skillTrackId: "footwork", name: "Split Steps", instructions: "Hop to a wide stance and land ready. 20 times.", difficulty: 1, durationSec: 90, xp: 5, isShadow: true },
    { id: "tn_side_shuffle", skillTrackId: "footwork", name: "Side Shuffles", instructions: "Shuffle 4 steps each way and shadow a swing at the end.", difficulty: 2, durationSec: 120, isShadow: true },
  ]),
  ...make("baseball", ["glove", "soft_ball"], [
    { id: "bs_target_throw", skillTrackId: "throwing", name: "Target Throws", instructions: "Throw at a spot on the wall. Point your glove, step, and throw.", difficulty: 2, durationSec: 150, needsWall: true, minSpace: "medium" },
    { id: "bs_long_toss", skillTrackId: "throwing", name: "Self Toss and Throw", instructions: "Toss the ball up, catch it, and throw at a far target.", difficulty: 3, durationSec: 180, minSpace: "large", xp: 12 },
    { id: "bs_shadow_throw", skillTrackId: "throwing", name: "Air Throws", instructions: "Step toward your target, turn your body, and follow through.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "bs_wall_grounders", skillTrackId: "fielding", name: "Wall Grounders", instructions: "Roll a tennis ball at the wall and field the bounce with your glove.", difficulty: 2, durationSec: 180, needsWall: true, equipmentRequired: ["glove", "tennis_ball"] },
    { id: "bs_pop_fly", skillTrackId: "fielding", name: "Pop-Fly Self Toss", instructions: "Toss the ball high, get under it, and catch above your head.", difficulty: 2, durationSec: 150, minSpace: "medium" },
    { id: "bs_shadow_field", skillTrackId: "fielding", name: "Alligator Hands", instructions: "Get low, glove down, top hand on top. Snap like an alligator.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
    { id: "bs_tee_swings", skillTrackId: "hitting", name: "Tee Swings", instructions: "Hit off the tee into a net or wall. Look at the ball the whole time.", difficulty: 2, durationSec: 240, equipmentRequired: ["bat", "tee", "soft_ball"], minSpace: "medium", xp: 12 },
    { id: "bs_shadow_swing", skillTrackId: "hitting", name: "Shadow Swings", instructions: "Load, step, swing level. 20 slow, 20 fast.", difficulty: 1, durationSec: 120, xp: 5, isShadow: true, equipmentOptional: ["bat"] },
    { id: "bs_base_steps", skillTrackId: "running", name: "Base Running Steps", instructions: "Sprint 10 steps, touch the front of an imaginary base, and turn.", difficulty: 2, durationSec: 120, minSpace: "medium", isShadow: true },
    { id: "bs_lead_off", skillTrackId: "running", name: "Lead-Off Shuffle", instructions: "Take 2 shuffle steps, then explode into a sprint. Repeat 8 times.", difficulty: 2, durationSec: 120, isShadow: true },
    { id: "bs_catcher_transfer", skillTrackId: "position", name: "Catch and Transfer", instructions: "Catch the ball in your glove and move it to your hand fast. 15 times.", difficulty: 3, durationSec: 150, positionIds: ["baseball_catcher", "baseball_infield"], xp: 12 },
    { id: "bs_pitch_balance", skillTrackId: "position", name: "Balance Point", instructions: "Lift your knee like a pitcher and hold for 3 seconds. Then step.", difficulty: 2, durationSec: 120, isShadow: true },
    { id: "bs_shadow_stance", skillTrackId: "position", name: "Ready Stance", instructions: "Feet wide, knees bent, glove out. Hold it, then shuffle.", difficulty: 1, durationSec: 60, xp: 5, isShadow: true },
  ]),
];
